name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ALTIS }}
          username: ${{ secrets.USERNAME_CHERNO }}
          port: ${{ secrets.PORT_ALTIS }}
          key: ${{ secrets.SSHKEY_ALTIS }}
          script: "cd /var/www/altis.1ns.at && chown -R root ../altis.1ns.at && ./.scripts/deploy-prod.sh && chown -R www-data ../altis.1ns.at"
