name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_CHERNO }}
          username: ${{ secrets.USERNAME_CHERNO }}
          port: ${{ secrets.PORT_CHERNO }}
          key: ${{ secrets.SSHKEY_CHERNO }}
          script: "cd /var/www/cherno.1ns.at && ./.scripts/deploy-prod.sh"
